export enum actions {
  GET_PRODUCTS = "GET_PRODUCTS",
  GET_PRODUCTS_RESPONSE = "GET_PRODUCTS_RESPONSE",
  GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR",
  SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT",
}
